[toolchain]

[features]
seeds = true
skip-lint = false

[programs.devnet]
counter = "6Jt2TKMTuejidRbctw4zGPmTMr7xcqsunRCA3DUHDBp3"

[programs.localnet]
counter = "6Jt2TKMTuejidRbctw4zGPmTMr7xcqsunRCA3DUHDBp3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = YOUR_WALLET_PATH

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
